Bug 1807237 - part 6: Fix jacocoFocusDebugTestReport gradle task
FAILURE: Build failed with an exception.

* Where:
Build file '/builds/worker/checkouts/vcs/focus-android/app/build.gradle' line: 613

* What went wrong:
A problem occurred configuring project ':app'.
> groovy.lang.GroovyRuntimeException: Cannot set the value of read-only property 'sourceDirectories' for task ':app:jacocoFocusDebugTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

(cherry picked from commit 98c6ba9aac224f69eb323e4933f1773a657d0670)