Set version to 110.1.0
Setting the version to 110.1.0, since 110.0.0 is not accepted:
File "/builds/worker/.local/lib/python3.8/site-packages/mozilla_version/gecko.py", line 223, in __attrs_post_init__
raise PatternNotMatchedError(self, patterns=error_messages)
mozilla_version.errors.PatternNotMatchedError: "110.0.0" does not match the pattern: Minor number and patch number cannot be both equal to 0